### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by schnittstabil** [sindresorhus/p-break#2]
FWIW, it smells a bit like `goto`:
[![GOTO](http://imgs.xkcd.com/comics/goto.png)](http://xkcd.com/292/)

Hence, introducing labels might be the next step:
```js
alwaysRun1()
    .then(() => alwaysRun2())
    .then(conditional1 => conditional1 || pBreak('🦄', 'label1'))
    .then(conditional2 => conditional2 || pBreak('🦄', 'label2'))
    .then(() => onlyRunConditional1())
    .then(() => onlyRunConditional2())
    .catch(pBreak.end('label1'))
    .then(() => onlyRunConditional3())
    .then(() => onlyRunConditional4())
    .catch(pBreak.end('label2'))
    .then(console.log);
```

– Totally spaghetti, in my opinion :wink:

**Comment by sindresorhus** [comment]
Lol, yeah. I'm still on the fence about this module, but adding labels is taking it too far. It would take it from being an easy & lazy shortcut to a fully blown goto-like nightmare.
